### ISSUE TITLE
iPhone X.      iPhone 6s.      iPad     13.5和13.7系统 通知里看不到此软件

### ISSUE THREAD

**Issue by lbopenwrt** [SmileZXLee/OpenDingTalkHelperForiOS#4]
在通知里面都看不到 钉钉打卡助手  这款软件  第一次打开软件均没有提示打开通知的请求 已测试多台设备。

**Comment by SmileZXLee** [comment]
> 在通知里面都看不到 钉钉打卡助手 这款软件 第一次打开软件均没有提示打开通知的请求 已测试多台设备。

感谢您的反馈，很抱歉给您带来不便了，我在新版本中修复了这一问题，劳烦您更新以后再测试一下，感谢！

**Comment by lbopenwrt** [comment]
经测试，可以正常跳转，感谢！

**Comment by 3v745** [comment]
iPhone7 13.5版本 修改时间为24小时后 反复提醒请将时间设置为24小时制

**Comment by SmileZXLee** [comment]
> iPhone7 13.5版本 修改时间为24小时后 反复提醒请将时间设置为24小时制
可以提供相关录屏和截图吗？

**Comment by SmileZXLee** [comment]
> iPhone7 13.5版本 修改时间为24小时后 反复提醒请将时间设置为24小时制

可以提供相关录屏和截图以便我定位问题吗？谢谢！

**Comment by 3v745** [comment]
> > iPhone7 13.5版本 修改时间为24小时后 反复提醒请将时间设置为24小时制
> 
> 可以提供相关录屏和截图以便我定位问题吗？谢谢！

问题已经解决，之前手机地区是日本 更改回中国大陆 已经正常
