### ISSUE TITLE
老哥，这个成本太高了

### ISSUE THREAD

**Issue by birdmichael** [SmileZXLee/OpenDingTalkHelperForiOS#7]
。。。。。。
本来是为了漏打卡，但是添加这个的成本是，我还需要记得前一天打开软件。。因为跳转到钉钉后，没办法自动跳回来。。。
感觉用闹钟+捷径靠谱点。。。。
我现在优化成，每天打卡最低时间，打开插件，然后最迟时间，打开其他任意app。（主要是偷懒不用写随机时间）

**Comment by SmileZXLee** [comment]
确实操作成本很高，因为App没有足够的权限，没办法跳到钉钉以后主动跳回来。
闹钟+捷径是个很好的办法，我在下一个版本中添加一下一天设置早晚上打卡时间的支持，并且搭配闹钟+捷径可以达到每天全自动打卡的效果。
感谢您提供的思路！

**Comment by birdmichael** [comment]
其实。。。一共代码改下来就5分钟。多一个下班时间设置。。
然后捷径上添加2个自动化-> 打开助手。完事。（不知道自动化能不能一键导入）
最好再加一个`exit(0)`杀死程序的入口。。
这样打卡了就自动回到桌面了。。不然一直在那个页面或者在解锁页面有点蠢。

**Comment by birdmichael** [comment]
晕了，连续2天出事故了。。
今天不知道为什么，快捷指令又没有运行。。。
再次优化。。。
下班时间，快捷指令打开钉钉，一分钟后再次打开助手。。。还是让助手一直常驻吧

**Comment by birdmichael** [comment]
老哥，app都打开了，但是没有通过急速打卡是什么原因呢？
搞自动打卡导致这周都天天没打卡了

**Comment by SmileZXLee** [comment]
可以加QQ群790460711或者我的微信交流一下细节哈。

**Comment by maojqxaut** [comment]
亲 ，这个不能同时设置上下班打卡时间吗，只能设置上班或者下班一个哦

**Comment by SmileZXLee** [comment]
> 亲 ，这个不能同时设置上下班打卡时间吗，只能设置上班或者下班一个哦

现已支持，可以更新一下哦
